"""Exposes a URL that specifies the behavior of this scalar."""
directive @specifiedBy(
  """The URL that specifies the behavior of this scalar."""
  url: String!
) on SCALAR

type AlreadyExistError implements Error {
  message: String!
}

type BaseError implements Error {
  message: String!
}

input CreateGameInput {
  gameId: String!
  playerName: String!
  playerTeam: TeamColor!
}

interface Error {
  message: String!
}

type Game {
  currentRound: Int!
  currentScore: Int!
  id: ID!
  rounds: Int!
  status: GameStatus!
  teams: [Team!]!
}

enum GameStatus {
  FINISHED
  LOBBY
  RUNNING
}

type Mutation {
  createGame(gameInput: CreateGameInput!): MutationCreateGameResult!
  joinToGame(playerName: String!, teamId: ID!): Player!
  sendAnswer: Float!
}

union MutationCreateGameResult = AlreadyExistError | BaseError | MutationCreateGameSuccess

type MutationCreateGameSuccess {
  data: Game!
}

type Player {
  id: ID!
  name: String!
  team: Team!
}

type Query {
  me: Player!
  test(asd: TeamColor!): TeamColor!
}

type Subscription {
  gameState(gameId: String!): Game!
  players(gameId: String!): [Player!]!
}

type Team {
  color: String!
  id: ID!
  players: [Player!]!
}

enum TeamColor {
  BLUE
  RED
}

