#!/bin/bash

# check if Node.js in version >= 18.5 is installed. If no, install it.
if ! command -v node &> /dev/null
then
    echo "Node.js could not be found. Installing..."
    curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
    sudo apt-get install -y nodejs
fi

# check if pnpm is installed. If no, install it.
if ! command -v pnpm &> /dev/null
then
    echo "pnpm could not be found. Installing..."
    npm install -g pnpm
fi

# check if docker is installed. If no, install it.
if ! command -v docker &> /dev/null
then
    echo "docker could not be found. Installing..."
    brew install --cask docker
fi

# check if docker-compose is installed. If no, install it.
if ! command -v docker-compose &> /dev/null
then
    echo "docker-compose could not be found. Installing..."
    brew install --cask docker-compose
fi

# Step 1: Install all dependencies
echo "Installing dependencies..."
pnpm i

# Step 2: Copy .env.example to .env in each /apps
echo "Copying .env.example to .env in each /apps..."
for dir in ./apps/*/
do
  cp "$dir".env.example "$dir".env
done

# Step 3: Run docker-compose up
echo "Running docker-compose up..."
docker-compose up -d

# Step 4: Run migrations
echo "Running migrations..."
pnpm -w run migrate

# Step 5: Run pnpm run dev
echo "Running pnpm run dev..."
pnpm run dev