#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm exec lint-staged

# TODO this should be per staged file but it's hard to achive 
# TODO fix it, now it's exploding because pnpm-lock.yaml is using version '6.0' instead of 5.4e
# pnpm run type-check
